# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "strcmp"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ross Bayer"]
  s.date = "2013-03-05"
  s.description = "A simple ruby gem that is used to compute how similar two strings are to one another. It includes a fast C implementation of the jaro-winkler distance algorith and soon the levenshtein distance algorithm. More metrics on the way."
  s.email = "rostepher.dev@gmail.com"
  s.extensions = ["ext/strcmp/extconf.rb"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "VERSION",
    "ext/strcmp/.gitignore",
    "ext/strcmp/extconf.rb",
    "ext/strcmp/jaro_winkler",
    "ext/strcmp/jaro_winkler.c",
    "ext/strcmp/jaro_winkler.h",
    "ext/strcmp/test.c",
    "lib/strcmp.rb",
    "spec/jaro_winkler_spec.rb",
    "spec/spec_helper.rb",
    "strcmp.gemspec"
  ]
  s.homepage = "http://github.com/Rostepher/strcmp"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "A gem to compare strings and compute a distance or other metric between two strings."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ffi>, ["~> 1.1.5"])
      s.add_runtime_dependency(%q<ffi>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<ffi>, ["~> 1.1.5"])
      s.add_dependency(%q<ffi>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<ffi>, ["~> 1.1.5"])
    s.add_dependency(%q<ffi>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

